# Default values for alb-ingress-default.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/turner/simple-backend
  tag: "1.0"
  pullPolicy: IfNotPresent

logzio: stderr

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 8080

ingress:
  certArn: arn:aws:acm:us-east-1:175259281135:certificate/e6b263d1-7074-4830-86d1-dd2eec1aaaa6
  path: /*
