# Default values for alb-ingress-default.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

deployment:
  create: true

image:
  url: quay.io/turner/simple-backend:1.0
  pullPolicy: IfNotPresent

logzio: stderr

monitoring:
  enabled: "true"
  kb_article: ""

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 8080

ingress:
  name: ""
  certArn: arn:aws:acm:us-east-1:175259281135:certificate/4455f959-06a7-4177-97b9-ec87c089e58b
  path: /*
