{{- $fallbackName := printf "%s-%" .Values.namespace .Values.ingress.type -}}
{{- $fallbackSelector := printf "%s-%s" .Values.namespace .Values.ingress.type -}}
{{- $ingressName := .Values.ingress.name | default $fallbackName -}}
{{- $ingressSelector := .Values.ingress.name | default $fallbackSelector -}}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ $ingressName }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.ingress.name | default (include "alb-ingress-default.name" .)  }}
    chart: {{ include "alb-ingress-default.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    appSelector: {{ $ingressSelector }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.ingress.name | default (include "alb-ingress-default.name" .)  }}
      release: {{ .Release.Name }}
      appSelector: {{ $ingressSelector }}
  template:
    metadata:
      labels:
        app: {{ .Values.ingress.name | default (include "alb-ingress-default.name" .)  }}
        release: {{ .Release.Name }}
        appSelector: {{ $ingressSelector }}
        logzio: {{ .Values.logzio }}
    spec:
      containers:
        - name: {{ $ingressName }}-backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
