{{- $project := .Values.project -}}
{{- $environment := .Values.environment -}}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ $project }}-{{ $environment }}-backend
  namespace: {{ $project }}-{{ $environment }}
  labels:
    app: {{ include "alb-ingress-default.name" . }}
    chart: {{ include "alb-ingress-default.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    appSelector: deployment-{{ $project }}-{{ $environment }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "alb-ingress-default.name" . }}
      release: {{ .Release.Name }}
      appSelector: deployment-{{ $project }}-{{ $environment }}-backend
  template:
    metadata:
      labels:
        app: {{ include "alb-ingress-default.name" . }}
        release: {{ .Release.Name }}
        appSelector: deployment-{{ $project }}-{{ $environment }}-backend
        logzio: {{ .Values.logzio }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
