{{- $namespace := .Values.namespace -}}
{{- $ingressType := .Values.ingress.type -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $port := .Values.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $namespace }}-{{ $ingressType }}-shared
  namespace: {{ $namespace }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=alb-logs-news-prod-dx,access_logs.s3.prefix={{ $namespace }}-shared
    alb.ingress.kubernetes.io/listen-ports: "[{\"HTTPS\": 443, \"HTTP\": 80}]"
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certArn }}
    {{- if eq $ingressType "internal" }}
    alb.ingress.kubernetes.io/security-groups: news-prod-dx_internal
    {{- else if eq $ingressType "external" }}
    alb.ingress.kubernetes.io/security-groups: news-prod-dx_external
    {{- end}}
  labels:
    app: {{ include "alb-ingress-default.name" . }}
    chart: {{ include "alb-ingress-default.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
    - host: {{ $namespace }}-{{ $ingressType }}.cnnio.net
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $namespace }}-{{ $ingressType }}-backend-nodeport
              servicePort: {{ $port }}
