{{- if .Values.deployment.create -}}
{{- $fallbackName := printf "%s-%s-shared-%s" .Release.Namespace .Values.ingress.type .Values.ingress.cluster -}}
{{- $appName := .Values.overrideName | default $fallbackName -}}
{{- $port := .Values.deployment.port | default 8080 -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $appName }}-np
  namespace: {{ .Release.Namespace }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  {{- end }}
  labels:
    app: {{ include "alb-ingress-default.name" . }}
    chart: {{ include "alb-ingress-default.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    albIngressName: "default"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ $port }}
      protocol: TCP
      name: port
      targetPort: {{ $port }}
  selector:
    appSelector: dep-{{ $appName }}
{{- end }}
