{{- required "`project` not set" .Values.project -}}
{{- required "`environment` not set" .Values.environment -}}
{{- $project := .Values.project -}}
{{- $environment := .Values.environment -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $project }}-{{ $environment }}-backend-nodeport
  namespace: {{ $project }}-{{ $environment }}
  labels:
    app: {{ include "alb-ingress-default.name" . }}
    chart: {{ include "alb-ingress-default.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: 8080tcp1
      targetPort: {{ .Values.service.port }}
  selector:
    appSelector: deployment-{{ $project }}-{{ $environment }}-backend
