{{- if .Values.deployment.create -}}
{{- $fallbackName := printf "%s-%s-backend" .Release.Namespace .Values.ingress.type -}}
{{- $appName := .Values.overrideName | default $fallbackName -}}
{{- $port := .Values.deployment.port | default 8080 -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $appName }}-nodeport
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "alb-ingress-default.name" . }}
    chart: {{ include "alb-ingress-default.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    albIngressName: "default"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ $port }}
      protocol: TCP
      name: port
      targetPort: {{ $port }}
  selector:
    appSelector: deployment-{{ $appName }}
{{- end }}
