{{- $fallbackName := printf "%s-%s" .Values.namespace .Values.ingress.type -}}
{{- $fallbackSelector := printf "%s-%s" .Values.namespace .Values.ingress.type -}}
{{- $appName := .Values.app.name | default $fallbackName -}}
{{- $appSelector := .Values.app.name | default $fallbackSelector -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $appName }}-backend-nodeport
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "alb-ingress-default.name" . }}
    chart: {{ include "alb-ingress-default.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: 8080tcp1
      targetPort: {{ .Values.service.port }}
  selector:
    appSelector: deployment-{{ $appSelector }}-backend
