{{- required "`namespace` not set" .Values.namespace -}}
{{- required "`ingress.type` not set" .Values.ingress.type -}}
{{- $namespace := .Values.namespace -}}
{{- $ingressType := .Values.ingress.type -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $namespace }}-{{ $ingressType }}-backend-nodeport
  namespace: {{ $namespace }}
  labels:
    app: {{ include "alb-ingress-default.name" . }}
    chart: {{ include "alb-ingress-default.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: 8080tcp1
      targetPort: {{ .Values.service.port }}
  selector:
    appSelector: deployment-{{ $namespace }}-{{ $ingressType }}-backend
